apiVersion: v2 
appVersion: v0.16.2 #TODO: Add version from argocd-applicationset
name: argocd-applicationset
description: A chart to deploy ApplicationSet CR via Helm
type: application
version: 0.0.2
keywords:
  - argocd
maintainers:
  - name: AlbertasG
    email: grinkevicius.albertas@gmail.com
    